### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by CaptainNoBeard** [alopezlago/QuizBowlDiscordScoreTracker#11]
When running this in our club discord, whenever someone tries to buzz, the bot throws this error:

Exception from Discord.Net: Object reference not set to an instance of an object.
Stack trace:
   at QuizBowlDiscordScoreTracker.BotConfiguration.TryGetVoiceChannelName(String guildName, String textChannelName, String& voiceChannelName) in C:\Users\lev26\Downloads\QuizBowlDiscordScoreTracker-master\QuizBowlDiscordScoreTracker-master\QuizBowlDiscordScoreTracker\BotConfiguration.cs:line 63
   at QuizBowlDiscordScoreTracker.Bot.PromptNextPlayer(GameState state, ITextChannel textChannel) in C:\Users\lev26\Downloads\QuizBowlDiscordScoreTracker-master\QuizBowlDiscordScoreTracker-master\QuizBowlDiscordScoreTracker\Bot.cs:line 167
   at QuizBowlDiscordScoreTracker.Bot.OnMessageCreated(SocketMessage message) in C:\Users\lev26\Downloads\QuizBowlDiscordScoreTracker-master\QuizBowlDiscordScoreTracker-master\QuizBowlDiscordScoreTracker\Bot.cs:line 238
   at Discord.EventExtensions.InvokeAsync[T](AsyncEvent`1 eventHandler, T arg)
   at Discord.WebSocket.DiscordSocketClient.TimeoutWrap(String name, Func`1 action)

This is very likely because I don't know what is supposed to be in config.txt, a file that does not exist yet seems to be required to run the bot. I got around this with a blank file, but clearly that doesn't cut it. I just don't know what to do for config, as the readme has no instruction for it, but the project will not build without it.

**Comment by CaptainNoBeard** [comment]
turns out the problem was config. config has to contain:
 {
	"waitForRejoinMs": 10000,
	"muteDelayMs": 500,
	"buzzEmojis": [":buzz:"],
	"supportedChannels": {
		"server1": [{ text: "channel1", voice: "Voice Channel" }],
    		"server2": [{ text: "packet", voice: "Packet Voice" }, { text: "channel2" }],
	}
}

and mine was blank. Thanks Jonathen Settle for telling me how to fix this!
