### ISSUE TITLE
exportToUCSD doesn't work with only 1 team (index failure)

### ISSUE THREAD

**Issue by alopezlago** [alopezlago/QuizBowlDiscordScoreTracker#68]
exportToUCSD doesn't work with only 1 team in the game. Here is the error:

2020-11-30 01:03:36.264 +00:00 [ERR] Exception occurred on Discord.Net side
Discord.Commands.CommandException: Error occurred executing "exportToUCSD" for Alejandro Lopez-Lago#1599 in QuizBowlScorerTestServer/general.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'index')
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument)
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at QuizBowlDiscordScoreTracker.Scoresheet.UCSDGoogleSheetsGenerator.TryCreateScoresheet(GameState game, Uri sheetsUri, String sheetName) in C:\Users\Alejandro\Documents\Visual Studio 2017\Projects\QuizBowlDiscordScoreTracker\QuizBowlDiscordScoreTracker\Scoresheet\UCSDGoogleSheetsGenerator.cs:line 84
   at QuizBowlDiscordScoreTracker.Commands.ReaderCommandHandler.ExportToUCSD(String sheetsUrl, Int32 round) in C:\Users\Alejandro\Documents\Visual Studio 2017\Projects\QuizBowlDiscordScoreTracker\QuizBowlDiscordScoreTracker\Commands\ReaderCommandHandler.cs:line 293
   at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
   --- End of inner exception stack trace ---

**Comment by alopezlago** [comment]
I have a fix for this. I might include it in the next big fork, or split it off.
